plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\bueno\\Documents\\maestro-squad-builder\\squads\\caca-cliente\\prospects\\youglow-clinic\\previa"
publishOrigin = "default"
base = "C:\\Users\\bueno\\Documents\\maestro-squad-builder\\squads\\caca-cliente\\prospects\\youglow-clinic\\previa"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]